[package]
name = "nydus_absorb"
type = "bin"
authors = ["drone"]

[dependencies]
poseidon = { path = "../../lib/poseidon" }
poseidon_ctr_encryption = { path = "../../lib/poseidon-ctr-encryption" }
ec = { tag = "v0.1.2", git = "https://github.com/noir-lang/ec" }
indexed_merkle_tree = { path = "../../lib/indexed-merkle-tree" }
